# .github/workflows/netlify.yml
name: mywallet
on:
 push:
  branchs:
   - main
 pull_request:
   branchs:
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: mywallet-project
        run: curl -X POST -d {}  ${{ secrets.NETFILY_BUILD_HOOK}}
